"""add raw materials

Revision ID: 01948b0c9a44
Revises: f344dcfcc97a
Create Date: 2026-05-26 22:02:57.502203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01948b0c9a44'
down_revision: Union[str, Sequence[str], None] = 'f344dcfcc97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'L', 'G', 'ML', name='unittype'), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_materials_id'), 'raw_materials', ['id'], unique=False)
    op.create_index(op.f('ix_raw_materials_name'), 'raw_materials', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_materials_name'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_id'), table_name='raw_materials')
    op.drop_table('raw_materials')
    # ### end Alembic commands ###
