"""Add customers

Revision ID: 14f255d893df
Revises: b1556713f719
Create Date: 2026-08-25 17:43:08.458056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f255d893df'
down_revision: Union[str, Sequence[str], None] = 'b1556713f719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('dietary_preferences', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chef_instructions', sa.String(length=1000), nullable=True),
    sa.Column('calorie_profile', sa.JSON(), nullable=True),
    sa.Column('selected_plan_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.Enum('ONBOARDING', 'PENDING_PLAN', 'ACTIVE', 'INACTIVE', name='customerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selected_plan_id'], ['plan_tiers.ulid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_ulid'), 'customers', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_ulid'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
