"""Add raw material cost tracking and logs

Revision ID: 1864bc25e11e
Revises: 2a350407c89d
Create Date: 2026-08-23 20:16:11.790216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1864bc25e11e'
down_revision: Union[str, Sequence[str], None] = '2a350407c89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_cost_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('previous_standard_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_standard_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('previous_actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('previous_yield_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_yield_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_cost_logs_id'), 'raw_material_cost_logs', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_cost_logs_raw_material_id'), 'raw_material_cost_logs', ['raw_material_id'], unique=False)
    op.create_index(op.f('ix_raw_material_cost_logs_ulid'), 'raw_material_cost_logs', ['ulid'], unique=True)
    op.add_column('raw_materials', sa.Column('standard_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('yield_grams', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('yield_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('previous_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'previous_price')
    op.drop_column('raw_materials', 'yield_percentage')
    op.drop_column('raw_materials', 'yield_grams')
    op.drop_column('raw_materials', 'actual_price')
    op.drop_column('raw_materials', 'standard_price')
    op.drop_index(op.f('ix_raw_material_cost_logs_ulid'), table_name='raw_material_cost_logs')
    op.drop_index(op.f('ix_raw_material_cost_logs_raw_material_id'), table_name='raw_material_cost_logs')
    op.drop_index(op.f('ix_raw_material_cost_logs_id'), table_name='raw_material_cost_logs')
    op.drop_table('raw_material_cost_logs')
    # ### end Alembic commands ###
