"""Add orders tables

Revision ID: 19d7b9214350
Revises: 8e3199d7a2a9
Create Date: 2026-08-29 02:11:14.635515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d7b9214350'
down_revision: Union[str, Sequence[str], None] = '8e3199d7a2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('order_source', sa.Enum('CUSTOM', 'PLAN', name='ordersource'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PREPARED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('total_order_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_plan_id'), 'orders', ['plan_id'], unique=False)
    op.create_index(op.f('ix_orders_target_date'), 'orders', ['target_date'], unique=False)
    op.create_index(op.f('ix_orders_ulid'), 'orders', ['ulid'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('bowl_id', sa.Integer(), nullable=False),
    sa.Column('meal_slot', sa.String(length=50), nullable=False),
    sa.Column('adjusted_calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjusted_macros', sa.JSON(), nullable=False),
    sa.Column('adjusted_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjusted_ingredients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bowl_id'], ['bowls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_bowl_id'), 'order_items', ['bowl_id'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_ulid'), 'order_items', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_ulid'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_bowl_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_ulid'), table_name='orders')
    op.drop_index(op.f('ix_orders_target_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_plan_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
