"""Add BowlCategory and Bowl models

Revision ID: 1bdad24a7c45
Revises: f59a0f260ffa
Create Date: 2026-06-26 00:22:50.952868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdad24a7c45'
down_revision: Union[str, Sequence[str], None] = 'f59a0f260ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bowl_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('background_image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bowl_categories_code'), 'bowl_categories', ['code'], unique=True)
    op.create_index(op.f('ix_bowl_categories_id'), 'bowl_categories', ['id'], unique=False)
    op.create_index(op.f('ix_bowl_categories_name'), 'bowl_categories', ['name'], unique=True)
    op.create_index(op.f('ix_bowl_categories_ulid'), 'bowl_categories', ['ulid'], unique=True)
    op.create_table('bowls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['bowl_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bowls_category_id'), 'bowls', ['category_id'], unique=False)
    op.create_index(op.f('ix_bowls_code'), 'bowls', ['code'], unique=True)
    op.create_index(op.f('ix_bowls_id'), 'bowls', ['id'], unique=False)
    op.create_index(op.f('ix_bowls_name'), 'bowls', ['name'], unique=False)
    op.create_index(op.f('ix_bowls_ulid'), 'bowls', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bowls_ulid'), table_name='bowls')
    op.drop_index(op.f('ix_bowls_name'), table_name='bowls')
    op.drop_index(op.f('ix_bowls_id'), table_name='bowls')
    op.drop_index(op.f('ix_bowls_code'), table_name='bowls')
    op.drop_index(op.f('ix_bowls_category_id'), table_name='bowls')
    op.drop_table('bowls')
    op.drop_index(op.f('ix_bowl_categories_ulid'), table_name='bowl_categories')
    op.drop_index(op.f('ix_bowl_categories_name'), table_name='bowl_categories')
    op.drop_index(op.f('ix_bowl_categories_id'), table_name='bowl_categories')
    op.drop_index(op.f('ix_bowl_categories_code'), table_name='bowl_categories')
    op.drop_table('bowl_categories')
    # ### end Alembic commands ###
