"""add yield_weight to ingredients

Revision ID: 206d52a13fc1
Revises: 84ff61d01679
Create Date: 2026-09-07 20:14:18.006746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206d52a13fc1'
down_revision: Union[str, Sequence[str], None] = '84ff61d01679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('yield_weight', sa.Numeric(precision=10, scale=2), nullable=True))

    # Update bowl trigger to use yield_weight for calculation
    op.execute('''
    CREATE OR REPLACE FUNCTION update_bowl_on_ingredient_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE bowls b
        SET 
            raw_cost = COALESCE(subquery.raw_cost, 0.0),
            total_cost = COALESCE(subquery.raw_cost, 0.0) + b.fixed_cost + COALESCE((SELECT total_cost FROM packaging WHERE id = b.packaging_id), 0.0)
        FROM (
            SELECT 
                bi.bowl_id,
                SUM((i.total_price / NULLIF(COALESCE(i.yield_weight, i.total_weight), 0)) * bi.weight_g_or_ml) AS raw_cost
            FROM bowl_ingredients bi
            JOIN ingredients i ON i.id = bi.ingredient_id
            WHERE bi.bowl_id IN (
                SELECT bowl_id FROM bowl_ingredients WHERE ingredient_id = NEW.id
            )
            GROUP BY bi.bowl_id
        ) AS subquery
        WHERE b.id = subquery.bowl_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    ''')

    op.execute("DROP TRIGGER IF EXISTS trigger_update_bowl_on_ingredient_update ON ingredients;")
    op.execute('''
    CREATE TRIGGER trigger_update_bowl_on_ingredient_update
    AFTER UPDATE OF total_price, total_weight, yield_weight ON ingredients
    FOR EACH ROW
    EXECUTE FUNCTION update_bowl_on_ingredient_update();
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'yield_weight')

    # Revert bowl trigger
    op.execute('''
    CREATE OR REPLACE FUNCTION update_bowl_on_ingredient_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE bowls b
        SET 
            raw_cost = COALESCE(subquery.raw_cost, 0.0),
            total_cost = COALESCE(subquery.raw_cost, 0.0) + b.fixed_cost + COALESCE((SELECT total_cost FROM packaging WHERE id = b.packaging_id), 0.0)
        FROM (
            SELECT 
                bi.bowl_id,
                SUM((i.total_price / NULLIF(i.total_weight, 0)) * bi.weight_g_or_ml) AS raw_cost
            FROM bowl_ingredients bi
            JOIN ingredients i ON i.id = bi.ingredient_id
            WHERE bi.bowl_id IN (
                SELECT bowl_id FROM bowl_ingredients WHERE ingredient_id = NEW.id
            )
            GROUP BY bi.bowl_id
        ) AS subquery
        WHERE b.id = subquery.bowl_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    ''')

    op.execute("DROP TRIGGER IF EXISTS trigger_update_bowl_on_ingredient_update ON ingredients;")
    op.execute('''
    CREATE TRIGGER trigger_update_bowl_on_ingredient_update
    AFTER UPDATE OF total_price, total_weight ON ingredients
    FOR EACH ROW
    EXECUTE FUNCTION update_bowl_on_ingredient_update();
    ''')
    # ### end Alembic commands ###
