"""Add updated_at to logs via TimestampMixin

Revision ID: 236fb457d162
Revises: 49db966e443a
Create Date: 2026-08-23 21:45:54.291316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236fb457d162'
down_revision: Union[str, Sequence[str], None] = '49db966e443a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('raw_material_cost_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('raw_material_stock_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_material_stock_logs', 'updated_at')
    op.drop_column('raw_material_cost_logs', 'updated_at')
    op.drop_column('documents', 'updated_at')
    # ### end Alembic commands ###
