"""Add zone_id to customer

Revision ID: 2bb8fbabf0de
Revises: ff269fbd1ba6
Create Date: 2026-09-15 00:05:04.005047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb8fbabf0de'
down_revision: Union[str, Sequence[str], None] = 'ff269fbd1ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'zone_id')
    # ### end Alembic commands ###
