"""Add ingredients models

Revision ID: 2bcdcf38ed97
Revises: e6c654ca6a80
Create Date: 2026-06-21 15:53:45.327555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcdcf38ed97'
down_revision: Union[str, Sequence[str], None] = 'e6c654ca6a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('background_image_filename', sa.String(length=255), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fiber', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_code'), 'ingredients', ['code'], unique=True)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_index(op.f('ix_ingredients_ulid'), 'ingredients', ['ulid'], unique=True)
    op.create_table('ingredient_raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('weight_g_or_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_raw_materials_id'), 'ingredient_raw_materials', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_raw_materials_ingredient_id'), 'ingredient_raw_materials', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_ingredient_raw_materials_raw_material_id'), 'ingredient_raw_materials', ['raw_material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_raw_materials_raw_material_id'), table_name='ingredient_raw_materials')
    op.drop_index(op.f('ix_ingredient_raw_materials_ingredient_id'), table_name='ingredient_raw_materials')
    op.drop_index(op.f('ix_ingredient_raw_materials_id'), table_name='ingredient_raw_materials')
    op.drop_table('ingredient_raw_materials')
    op.drop_index(op.f('ix_ingredients_ulid'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_code'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
