"""Add DailyPrepTask for KDS

Revision ID: 34fb5151b0ec
Revises: 852e83c118a2
Create Date: 2026-08-30 01:07:33.242293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fb5151b0ec'
down_revision: Union[str, Sequence[str], None] = '852e83c118a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_prep_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNCOOKED', 'PREPARING', 'PREPARED', name='prepstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_date', 'ingredient_id', name='uix_target_date_ingredient')
    )
    op.create_index(op.f('ix_daily_prep_tasks_id'), 'daily_prep_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_daily_prep_tasks_ingredient_id'), 'daily_prep_tasks', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_daily_prep_tasks_target_date'), 'daily_prep_tasks', ['target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_prep_tasks_target_date'), table_name='daily_prep_tasks')
    op.drop_index(op.f('ix_daily_prep_tasks_ingredient_id'), table_name='daily_prep_tasks')
    op.drop_index(op.f('ix_daily_prep_tasks_id'), table_name='daily_prep_tasks')
    op.drop_table('daily_prep_tasks')
    # ### end Alembic commands ###
