"""add_packaging_code

Revision ID: 49db966e443a
Revises: 868e86de7479
Create Date: 2026-08-23 21:20:31.885840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49db966e443a'
down_revision: Union[str, Sequence[str], None] = '868e86de7479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packaging', sa.Column('code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_packaging_code'), 'packaging', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packaging_code'), table_name='packaging')
    op.drop_column('packaging', 'code')
    # ### end Alembic commands ###
