"""Add packaging, bowl builder, and triggers

Revision ID: 59fc79f6927f
Revises: 7eb9fdcfda0c
Create Date: 2026-08-03 00:59:25.017685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fc79f6927f'
down_revision: Union[str, Sequence[str], None] = '7eb9fdcfda0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_id'), 'packaging', ['id'], unique=False)
    op.create_index(op.f('ix_packaging_name'), 'packaging', ['name'], unique=True)
    op.create_index(op.f('ix_packaging_ulid'), 'packaging', ['ulid'], unique=True)
    op.create_table('packaging_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_components_id'), 'packaging_components', ['id'], unique=False)
    op.create_index(op.f('ix_packaging_components_name'), 'packaging_components', ['name'], unique=True)
    op.create_index(op.f('ix_packaging_components_ulid'), 'packaging_components', ['ulid'], unique=True)
    op.create_table('packaging_item_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['packaging_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packaging_id'], ['packaging.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.execute("DO $$ BEGIN CREATE TYPE bowlsection AS ENUM ('DRESSING', 'BLENDS', 'ADD_ONS', 'PROTEIN', 'CARB', 'FIBER', 'EXTRA_PROTEIN'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE bowltype AS ENUM ('STANDARD', 'CUSTOM'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_index(op.f('ix_packaging_item_links_component_id'), 'packaging_item_links', ['component_id'], unique=False)
    op.create_index(op.f('ix_packaging_item_links_id'), 'packaging_item_links', ['id'], unique=False)
    op.create_index(op.f('ix_packaging_item_links_packaging_id'), 'packaging_item_links', ['packaging_id'], unique=False)

    from sqlalchemy.dialects import postgresql
    op.create_table('bowl_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bowl_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('section_name', postgresql.ENUM('DRESSING', 'BLENDS', 'ADD_ONS', 'PROTEIN', 'CARB', 'FIBER', 'EXTRA_PROTEIN', name='bowlsection', create_type=False), nullable=False),
    sa.Column('weight_g_or_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bowl_id'], ['bowls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bowl_ingredients_bowl_id'), 'bowl_ingredients', ['bowl_id'], unique=False)
    op.create_index(op.f('ix_bowl_ingredients_id'), 'bowl_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_bowl_ingredients_ingredient_id'), 'bowl_ingredients', ['ingredient_id'], unique=False)
    op.add_column('bowls', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('bowls', sa.Column('bowl_type', postgresql.ENUM('STANDARD', 'CUSTOM', name='bowltype', create_type=False), nullable=False))
    op.add_column('bowls', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('bowls', sa.Column('raw_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bowls', sa.Column('fixed_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bowls', sa.Column('packaging_id', sa.Integer(), nullable=True))
    op.add_column('bowls', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'bowls', 'packaging', ['packaging_id'], ['id'], ondelete='SET NULL')
    
    # --- Custom PostgreSQL Triggers for Price Cascading ---
    
    # 1. Raw Material -> Ingredient
    op.execute("""
    CREATE OR REPLACE FUNCTION update_ingredient_on_raw_material_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE ingredients i
        SET 
            total_weight = subquery.total_weight,
            total_price = subquery.total_price,
            total_calories = subquery.total_calories,
            total_protein = subquery.total_protein,
            total_carbs = subquery.total_carbs,
            total_fat = subquery.total_fat,
            total_fiber = subquery.total_fiber
        FROM (
            SELECT 
                irm.ingredient_id,
                SUM(irm.weight_g_or_ml) AS total_weight,
                SUM((r.price / CASE WHEN r.unit IN ('KG', 'L') THEN 1000.0 ELSE 1.0 END) * irm.weight_g_or_ml) AS total_price,
                SUM(COALESCE(r.calories, 0) * (irm.weight_g_or_ml / 100.0)) AS total_calories,
                SUM(COALESCE(r.protein, 0) * (irm.weight_g_or_ml / 100.0)) AS total_protein,
                SUM(COALESCE(r.carbs, 0) * (irm.weight_g_or_ml / 100.0)) AS total_carbs,
                SUM(COALESCE(r.fat, 0) * (irm.weight_g_or_ml / 100.0)) AS total_fat,
                SUM(COALESCE(r.fiber, 0) * (irm.weight_g_or_ml / 100.0)) AS total_fiber
            FROM ingredient_raw_materials irm
            JOIN raw_materials r ON r.id = irm.raw_material_id
            WHERE irm.ingredient_id IN (
                SELECT ingredient_id FROM ingredient_raw_materials WHERE raw_material_id = NEW.id
            )
            GROUP BY irm.ingredient_id
        ) AS subquery
        WHERE i.id = subquery.ingredient_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_update_ingredient_on_raw_material_update
    AFTER UPDATE OF price, calories, protein, carbs, fat, fiber ON raw_materials
    FOR EACH ROW
    EXECUTE FUNCTION update_ingredient_on_raw_material_update();
    """)
    
    # 2. Ingredient -> Bowl
    op.execute("""
    CREATE OR REPLACE FUNCTION update_bowl_on_ingredient_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE bowls b
        SET 
            raw_cost = COALESCE(subquery.raw_cost, 0.0),
            total_cost = COALESCE(subquery.raw_cost, 0.0) + b.fixed_cost + COALESCE((SELECT total_cost FROM packaging WHERE id = b.packaging_id), 0.0)
        FROM (
            SELECT 
                bi.bowl_id,
                SUM((i.total_price / NULLIF(i.total_weight, 0)) * bi.weight_g_or_ml) AS raw_cost
            FROM bowl_ingredients bi
            JOIN ingredients i ON i.id = bi.ingredient_id
            WHERE bi.bowl_id IN (
                SELECT bowl_id FROM bowl_ingredients WHERE ingredient_id = NEW.id
            )
            GROUP BY bi.bowl_id
        ) AS subquery
        WHERE b.id = subquery.bowl_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_update_bowl_on_ingredient_update
    AFTER UPDATE OF total_price, total_weight ON ingredients
    FOR EACH ROW
    EXECUTE FUNCTION update_bowl_on_ingredient_update();
    """)
    
    # 3. Packaging Component -> Packaging
    op.execute("""
    CREATE OR REPLACE FUNCTION update_packaging_on_component_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE packaging p
        SET total_cost = subquery.total_cost
        FROM (
            SELECT 
                pil.packaging_id,
                SUM(pc.cost * pil.quantity) AS total_cost
            FROM packaging_item_links pil
            JOIN packaging_components pc ON pc.id = pil.component_id
            WHERE pil.packaging_id IN (
                SELECT packaging_id FROM packaging_item_links WHERE component_id = NEW.id
            )
            GROUP BY pil.packaging_id
        ) AS subquery
        WHERE p.id = subquery.packaging_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_update_packaging_on_component_update
    AFTER UPDATE OF cost ON packaging_components
    FOR EACH ROW
    EXECUTE FUNCTION update_packaging_on_component_update();
    """)
    
    # 4. Packaging -> Bowl
    op.execute("""
    CREATE OR REPLACE FUNCTION update_bowl_on_packaging_update()
    RETURNS TRIGGER AS $$
    BEGIN
        UPDATE bowls b
        SET total_cost = b.raw_cost + b.fixed_cost + NEW.total_cost
        WHERE b.packaging_id = NEW.id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_update_bowl_on_packaging_update
    AFTER UPDATE OF total_cost ON packaging
    FOR EACH ROW
    EXECUTE FUNCTION update_bowl_on_packaging_update();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bowls', type_='foreignkey')
    op.drop_column('bowls', 'total_cost')
    op.drop_column('bowls', 'packaging_id')
    op.drop_column('bowls', 'fixed_cost')
    op.drop_column('bowls', 'raw_cost')
    op.drop_column('bowls', 'status')
    op.drop_column('bowls', 'bowl_type')
    op.drop_column('bowls', 'description')
    op.drop_index(op.f('ix_bowl_ingredients_ingredient_id'), table_name='bowl_ingredients')
    op.drop_index(op.f('ix_bowl_ingredients_id'), table_name='bowl_ingredients')
    op.drop_index(op.f('ix_bowl_ingredients_bowl_id'), table_name='bowl_ingredients')
    op.drop_table('bowl_ingredients')
    op.drop_index(op.f('ix_packaging_item_links_packaging_id'), table_name='packaging_item_links')
    op.drop_index(op.f('ix_packaging_item_links_id'), table_name='packaging_item_links')
    op.drop_index(op.f('ix_packaging_item_links_component_id'), table_name='packaging_item_links')
    op.drop_table('packaging_item_links')
    op.drop_index(op.f('ix_packaging_components_ulid'), table_name='packaging_components')
    op.drop_index(op.f('ix_packaging_components_name'), table_name='packaging_components')
    op.drop_index(op.f('ix_packaging_components_id'), table_name='packaging_components')
    op.drop_table('packaging_components')
    # --- Drop Custom PostgreSQL Triggers ---
    op.execute("DROP TRIGGER IF EXISTS trigger_update_bowl_on_packaging_update ON packaging;")
    op.execute("DROP FUNCTION IF EXISTS update_bowl_on_packaging_update();")
    
    op.execute("DROP TRIGGER IF EXISTS trigger_update_packaging_on_component_update ON packaging_components;")
    op.execute("DROP FUNCTION IF EXISTS update_packaging_on_component_update();")
    
    op.execute("DROP TRIGGER IF EXISTS trigger_update_bowl_on_ingredient_update ON ingredients;")
    op.execute("DROP FUNCTION IF EXISTS update_bowl_on_ingredient_update();")
    
    op.execute("DROP TRIGGER IF EXISTS trigger_update_ingredient_on_raw_material_update ON raw_materials;")
    op.execute("DROP FUNCTION IF EXISTS update_ingredient_on_raw_material_update();")

    op.drop_index(op.f('ix_packaging_ulid'), table_name='packaging')
    op.drop_index(op.f('ix_packaging_name'), table_name='packaging')
    op.drop_index(op.f('ix_packaging_id'), table_name='packaging')
    op.drop_table('packaging')
    
    from sqlalchemy.dialects import postgresql
    postgresql.ENUM(name='bowlsection').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='bowltype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
