"""Add lat long to customer

Revision ID: 5c7b25c6bfc7
Revises: 34fb5151b0ec
Create Date: 2026-08-31 00:21:24.785051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7b25c6bfc7'
down_revision: Union[str, Sequence[str], None] = '34fb5151b0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('customers', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'longitude')
    op.drop_column('customers', 'latitude')
    # ### end Alembic commands ###
