"""add meal category table

Revision ID: 7eb9fdcfda0c
Revises: 1bdad24a7c45
Create Date: 2026-07-21 20:20:20.582324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb9fdcfda0c'
down_revision: Union[str, Sequence[str], None] = '1bdad24a7c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_categories_id'), 'meal_categories', ['id'], unique=False)
    op.create_index(op.f('ix_meal_categories_slug'), 'meal_categories', ['slug'], unique=True)
    op.create_index(op.f('ix_meal_categories_ulid'), 'meal_categories', ['ulid'], unique=True)
    op.add_column('bowls', sa.Column('meal_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bowls_meal_category_id'), 'bowls', ['meal_category_id'], unique=False)
    op.create_foreign_key(None, 'bowls', 'meal_categories', ['meal_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bowls', type_='foreignkey')
    op.drop_index(op.f('ix_bowls_meal_category_id'), table_name='bowls')
    op.drop_column('bowls', 'meal_category_id')
    op.drop_index(op.f('ix_meal_categories_ulid'), table_name='meal_categories')
    op.drop_index(op.f('ix_meal_categories_slug'), table_name='meal_categories')
    op.drop_index(op.f('ix_meal_categories_id'), table_name='meal_categories')
    op.drop_table('meal_categories')
    # ### end Alembic commands ###
