"""add_packaging_component_stock_management

Revision ID: 84ff61d01679
Revises: 5c7b25c6bfc7
Create Date: 2026-08-31 01:01:50.460402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ff61d01679'
down_revision: Union[str, Sequence[str], None] = '5c7b25c6bfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_component_stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_ulid', sa.String(length=26), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['packaging_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_component_stock_logs_component_id'), 'packaging_component_stock_logs', ['component_id'], unique=False)
    op.create_index(op.f('ix_packaging_component_stock_logs_id'), 'packaging_component_stock_logs', ['id'], unique=False)
    op.create_index(op.f('ix_packaging_component_stock_logs_ulid'), 'packaging_component_stock_logs', ['ulid'], unique=True)
    op.add_column('packaging_components', sa.Column('current_stock', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('packaging_components', sa.Column('stock_threshold', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packaging_components', 'stock_threshold')
    op.drop_column('packaging_components', 'current_stock')
    op.drop_index(op.f('ix_packaging_component_stock_logs_ulid'), table_name='packaging_component_stock_logs')
    op.drop_index(op.f('ix_packaging_component_stock_logs_id'), table_name='packaging_component_stock_logs')
    op.drop_index(op.f('ix_packaging_component_stock_logs_component_id'), table_name='packaging_component_stock_logs')
    op.drop_table('packaging_component_stock_logs')
    # ### end Alembic commands ###
