"""Add total_calories_ordered to customer

Revision ID: 852e83c118a2
Revises: 984c27a57ab8
Create Date: 2026-08-29 03:05:44.599357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852e83c118a2'
down_revision: Union[str, Sequence[str], None] = '984c27a57ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('total_calories_ordered', sa.Numeric(precision=15, scale=2), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'total_calories_ordered')
    # ### end Alembic commands ###
