"""add raw materials

Revision ID: 8ca6596d3f8c
Revises: 01948b0c9a44
Create Date: 2026-05-27 00:14:47.497366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca6596d3f8c'
down_revision: Union[str, Sequence[str], None] = '01948b0c9a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('item_code', sa.String(length=50), nullable=True))
    op.add_column('raw_materials', sa.Column('background_image_filename', sa.String(length=255), nullable=True))
    op.add_column('raw_materials', sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('protein', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('fiber', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('raw_materials', sa.Column('micros', sa.JSON(), nullable=True))
    op.add_column('raw_materials', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_raw_materials_item_code'), 'raw_materials', ['item_code'], unique=True)
    op.create_foreign_key(None, 'raw_materials', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_index(op.f('ix_raw_materials_item_code'), table_name='raw_materials')
    op.drop_column('raw_materials', 'created_by_id')
    op.drop_column('raw_materials', 'micros')
    op.drop_column('raw_materials', 'fat')
    op.drop_column('raw_materials', 'fiber')
    op.drop_column('raw_materials', 'carbs')
    op.drop_column('raw_materials', 'protein')
    op.drop_column('raw_materials', 'calories')
    op.drop_column('raw_materials', 'background_image_filename')
    op.drop_column('raw_materials', 'item_code')
    # ### end Alembic commands ###
