"""Add customer image_filename

Revision ID: 8e3199d7a2a9
Revises: 14f255d893df
Create Date: 2026-08-29 00:29:51.403842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3199d7a2a9'
down_revision: Union[str, Sequence[str], None] = '14f255d893df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('image_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'image_filename')
    # ### end Alembic commands ###
