"""Add created_by_id to Bowl

Revision ID: 96b43bbc09ac
Revises: f947f3c1f46d
Create Date: 2026-08-24 16:32:53.575885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b43bbc09ac'
down_revision: Union[str, Sequence[str], None] = 'f947f3c1f46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bowls', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bowls_created_by_id'), 'bowls', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'bowls', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bowls', type_='foreignkey')
    op.drop_index(op.f('ix_bowls_created_by_id'), table_name='bowls')
    op.drop_column('bowls', 'created_by_id')
    # ### end Alembic commands ###
