"""Add customer calorie log

Revision ID: 984c27a57ab8
Revises: 457032ed0367
Create Date: 2026-08-29 03:00:57.337052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984c27a57ab8'
down_revision: Union[str, Sequence[str], None] = '457032ed0367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_calorie_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('meal_slot', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_calorie_logs_customer_id'), 'customer_calorie_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_calorie_logs_id'), 'customer_calorie_logs', ['id'], unique=False)
    op.create_index(op.f('ix_customer_calorie_logs_order_id'), 'customer_calorie_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_customer_calorie_logs_target_date'), 'customer_calorie_logs', ['target_date'], unique=False)
    op.create_index(op.f('ix_customer_calorie_logs_ulid'), 'customer_calorie_logs', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_calorie_logs_ulid'), table_name='customer_calorie_logs')
    op.drop_index(op.f('ix_customer_calorie_logs_target_date'), table_name='customer_calorie_logs')
    op.drop_index(op.f('ix_customer_calorie_logs_order_id'), table_name='customer_calorie_logs')
    op.drop_index(op.f('ix_customer_calorie_logs_id'), table_name='customer_calorie_logs')
    op.drop_index(op.f('ix_customer_calorie_logs_customer_id'), table_name='customer_calorie_logs')
    op.drop_table('customer_calorie_logs')
    # ### end Alembic commands ###
