"""Add plan tiers

Revision ID: b1556713f719
Revises: c2e706a14272
Create Date: 2026-08-25 15:56:28.804728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1556713f719'
down_revision: Union[str, Sequence[str], None] = 'c2e706a14272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=255), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tiers_id'), 'plan_tiers', ['id'], unique=False)
    op.create_index(op.f('ix_plan_tiers_ulid'), 'plan_tiers', ['ulid'], unique=True)
    op.create_table('plan_tier_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_tier_id', sa.Integer(), nullable=False),
    sa.Column('meal_type_code', sa.String(length=10), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('bowl_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bowl_id'], ['bowls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_tier_id'], ['plan_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tier_selections_bowl_id'), 'plan_tier_selections', ['bowl_id'], unique=False)
    op.create_index(op.f('ix_plan_tier_selections_id'), 'plan_tier_selections', ['id'], unique=False)
    op.create_index(op.f('ix_plan_tier_selections_plan_tier_id'), 'plan_tier_selections', ['plan_tier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_tier_selections_plan_tier_id'), table_name='plan_tier_selections')
    op.drop_index(op.f('ix_plan_tier_selections_id'), table_name='plan_tier_selections')
    op.drop_index(op.f('ix_plan_tier_selections_bowl_id'), table_name='plan_tier_selections')
    op.drop_table('plan_tier_selections')
    op.drop_index(op.f('ix_plan_tiers_ulid'), table_name='plan_tiers')
    op.drop_index(op.f('ix_plan_tiers_id'), table_name='plan_tiers')
    op.drop_table('plan_tiers')
    # ### end Alembic commands ###
