"""Add raw material purchases

Revision ID: c2e706a14272
Revises: 96b43bbc09ac
Create Date: 2026-08-24 23:50:49.165280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c2e706a14272'
down_revision: Union[str, Sequence[str], None] = '96b43bbc09ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', postgresql.ENUM('KG', 'L', 'G', 'ML', name='unittype', create_type=False), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_purchases_id'), 'raw_material_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_purchases_raw_material_id'), 'raw_material_purchases', ['raw_material_id'], unique=False)
    op.create_index(op.f('ix_raw_material_purchases_ulid'), 'raw_material_purchases', ['ulid'], unique=True)
    op.create_index(op.f('ix_raw_material_purchases_vendor_id'), 'raw_material_purchases', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_material_purchases_vendor_id'), table_name='raw_material_purchases')
    op.drop_index(op.f('ix_raw_material_purchases_ulid'), table_name='raw_material_purchases')
    op.drop_index(op.f('ix_raw_material_purchases_raw_material_id'), table_name='raw_material_purchases')
    op.drop_index(op.f('ix_raw_material_purchases_id'), table_name='raw_material_purchases')
    op.drop_table('raw_material_purchases')
    # ### end Alembic commands ###
