"""Add raw material categories

Revision ID: cf5331450f2e
Revises: 2bcdcf38ed97
Create Date: 2026-06-25 02:08:02.934585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5331450f2e'
down_revision: Union[str, Sequence[str], None] = '2bcdcf38ed97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_categories_id'), 'raw_material_categories', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_categories_name'), 'raw_material_categories', ['name'], unique=True)
    op.create_index(op.f('ix_raw_material_categories_ulid'), 'raw_material_categories', ['ulid'], unique=True)
    op.add_column('raw_materials', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'raw_materials', 'raw_material_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_column('raw_materials', 'category_id')
    op.drop_index(op.f('ix_raw_material_categories_ulid'), table_name='raw_material_categories')
    op.drop_index(op.f('ix_raw_material_categories_name'), table_name='raw_material_categories')
    op.drop_index(op.f('ix_raw_material_categories_id'), table_name='raw_material_categories')
    op.drop_table('raw_material_categories')
    # ### end Alembic commands ###
