"""Add wallet and ledger models

Revision ID: d2c0cf7d6c7c
Revises: 999999999998
Create Date: 2026-09-14 22:55:30.060444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0cf7d6c7c'
down_revision: Union[str, Sequence[str], None] = '999999999998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('gross_price', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('billed_price', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('is_billed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('plan_tiers', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_tiers', 'discount_percentage')
    op.drop_column('orders', 'is_billed')
    op.drop_column('orders', 'billed_price')
    op.drop_column('orders', 'gross_price')
    op.drop_column('customers', 'wallet_balance')
    # ### end Alembic commands ###
