"""Add transaction ledger table

Revision ID: dd212580f150
Revises: d2c0cf7d6c7c
Create Date: 2026-09-14 23:19:05.366319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd212580f150'
down_revision: Union[str, Sequence[str], None] = 'd2c0cf7d6c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'DEBIT', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ledgers_customer_id'), 'transaction_ledgers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transaction_ledgers_id'), 'transaction_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_ledgers_ulid'), 'transaction_ledgers', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_ledgers_ulid'), table_name='transaction_ledgers')
    op.drop_index(op.f('ix_transaction_ledgers_id'), table_name='transaction_ledgers')
    op.drop_index(op.f('ix_transaction_ledgers_customer_id'), table_name='transaction_ledgers')
    op.drop_table('transaction_ledgers')
    # ### end Alembic commands ###
