"""remove file_url from documents

Revision ID: f344dcfcc97a
Revises: 8eaccaf1a700
Create Date: 2026-05-22 02:34:37.127098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f344dcfcc97a'
down_revision: Union[str, Sequence[str], None] = '8eaccaf1a700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
