"""Add stock management fields and logs

Revision ID: f59a0f260ffa
Revises: cf5331450f2e
Create Date: 2026-06-25 02:44:47.084605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59a0f260ffa'
down_revision: Union[str, Sequence[str], None] = 'cf5331450f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material_stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_stock_logs_id'), 'raw_material_stock_logs', ['id'], unique=False)
    op.create_index(op.f('ix_raw_material_stock_logs_raw_material_id'), 'raw_material_stock_logs', ['raw_material_id'], unique=False)
    op.create_index(op.f('ix_raw_material_stock_logs_ulid'), 'raw_material_stock_logs', ['ulid'], unique=True)
    op.add_column('raw_materials', sa.Column('current_stock', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('raw_materials', sa.Column('stock_threshold', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'stock_threshold')
    op.drop_column('raw_materials', 'current_stock')
    op.drop_index(op.f('ix_raw_material_stock_logs_ulid'), table_name='raw_material_stock_logs')
    op.drop_index(op.f('ix_raw_material_stock_logs_raw_material_id'), table_name='raw_material_stock_logs')
    op.drop_index(op.f('ix_raw_material_stock_logs_id'), table_name='raw_material_stock_logs')
    op.drop_table('raw_material_stock_logs')
    # ### end Alembic commands ###
