"""Add image_filename to Bowl

Revision ID: f947f3c1f46d
Revises: b2bfd74d7f20
Create Date: 2026-08-23 22:22:52.155611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f947f3c1f46d'
down_revision: Union[str, Sequence[str], None] = 'b2bfd74d7f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bowls', sa.Column('image_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bowls', 'image_filename')
    # ### end Alembic commands ###
