"""Add logistics models

Revision ID: ff269fbd1ba6
Revises: dd212580f150
Create Date: 2026-09-15 00:00:17.310342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff269fbd1ba6'
down_revision: Union[str, Sequence[str], None] = 'dd212580f150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=True)
    op.create_index(op.f('ix_drivers_ulid'), 'drivers', ['ulid'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('polygon_coordinates', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_index(op.f('ix_zones_ulid'), 'zones', ['ulid'], unique=True)
    op.add_column('orders', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'driver_id')
    op.drop_index(op.f('ix_zones_ulid'), table_name='zones')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_drivers_ulid'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
